set(QT_REPO_MODULE_VERSION "6.12.0")
set(QT_REPO_MODULE_PRERELEASE_VERSION_SEGMENT "alpha1")
set(QT_SUPPORTED_MIN_CMAKE_VERSION_FOR_BUILDING_WEBENGINE "3.19")
set(QT_EXTRA_INTERNAL_TARGET_DEFINES
    "QT_NO_FOREACH=1"
    "QT_NO_QASCONST=1"
    "QT_NO_QSNPRINTF=1"
    "QT_NO_SINGLE_ARGUMENT_QHASH_OVERLOAD=1"
)
