qt_commandline_option(webengine-alsa TYPE boolean NAME webengine-system-alsa)
qt_commandline_option(webengine-embedded-build TYPE boolean)
qt_commandline_option(webengine-icu TYPE enum NAME webengine-system-icu MAPPING system yes qt no)
qt_commandline_option(webengine-ffmpeg TYPE enum NAME webengine-system-ffmpeg MAPPING system yes qt no)
qt_commandline_option(webengine-opus TYPE enum NAME webengine-system-opus MAPPING system yes qt no)
qt_commandline_option(webengine-webp TYPE enum NAME webengine-system-libwebp MAPPING system yes qt no)
qt_commandline_option(webengine-pepper-plugins TYPE boolean)
qt_commandline_option(webengine-printing-and-pdf TYPE boolean)
qt_commandline_option(webengine-proprietary-codecs TYPE boolean)
qt_commandline_option(webengine-pulseaudio TYPE boolean NAME webengine-system-pulseaudio)
qt_commandline_option(webengine-spellchecker TYPE boolean)
qt_commandline_option(webengine-native-spellchecker TYPE boolean)
qt_commandline_option(webengine-webrtc TYPE boolean)
